version: "3.8"
services:
  flaskapp:
    container_name: flaskapp
    build:
      context: .
    ports:
      - "35000:5000"
    depends_on:
      - minio
      - postgres
    environment:
      FLASK_ENV: development

  minio:
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    ports:
      - "39000:9000"
      - "39001:9001"
    volumes:
      - minio_data:/data

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  busybox:
    image: nginx:alpine
    working_dir: /

volumes:
  minio_data:
  postgres_data:
